-- Run this file in the Supabase SQL editor before using the cloud database.
-- The service role is used only by server-side Next.js route handlers.

create table if not exists public.orders (
  order_id text primary key,
  phone text not null,
  plan_id text not null,
  plan_name text,
  money numeric(12, 2) not null check (money >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'refunded')),
  card_code text,
  provider_trade_no text,
  provider text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  plan_id text not null,
  card_code text not null unique,
  is_used smallint not null default 0 check (is_used in (0, 1)),
  order_id text references public.orders(order_id),
  created_at timestamptz not null default now()
);

create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create unique index if not exists orders_provider_trade_no_idx
  on public.orders(provider_trade_no)
  where provider_trade_no is not null;
create index if not exists cards_plan_stock_idx on public.cards(plan_id, is_used);
create index if not exists cards_created_at_idx on public.cards(created_at desc);

alter table public.orders enable row level security;
alter table public.cards enable row level security;

-- No public policies are created intentionally. All current access goes through
-- the server-side service-role client, never through the browser.

create or replace function public.mark_order_paid_and_assign_card(
  p_order_id text,
  p_trade_no text,
  p_money numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_card public.cards%rowtype;
begin
  select *
    into v_order
    from public.orders
   where order_id = p_order_id
   for update;

  if not found then
    raise exception 'order_not_found';
  end if;

  if v_order.money <> p_money then
    raise exception 'amount_mismatch';
  end if;

  if v_order.status = 'paid' then
    return jsonb_build_object(
      'status', 'paid',
      'card_code', v_order.card_code
    );
  end if;

  select *
    into v_card
    from public.cards
   where plan_id = v_order.plan_id
     and is_used = 0
   order by created_at asc
   for update skip locked
   limit 1;

  if not found then
    raise exception 'out_of_stock';
  end if;

  update public.cards
     set is_used = 1,
         order_id = v_order.order_id
   where id = v_card.id;

  update public.orders
     set status = 'paid',
         card_code = v_card.card_code,
         provider_trade_no = p_trade_no,
         provider = 'luckywood',
         paid_at = now()
   where order_id = v_order.order_id;

  return jsonb_build_object(
    'status', 'paid',
    'card_code', v_card.card_code
  );
end;
$$;

revoke all on function public.mark_order_paid_and_assign_card(text, text, numeric)
from public, anon, authenticated;
