-- 创建 CDK 兑换记录表
create table if not exists public.cdk_redemptions (
  id bigint generated by default as identity primary key,
  redemption_token text not null,
  card_code_hint text,
  email text,
  session_data text,
  plan text,
  order_id text,
  status text not null default 'pending'
    check (status in ('pending', 'completed', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists cdk_redemptions_created_at_idx on public.cdk_redemptions(created_at desc);
create index if not exists cdk_redemptions_email_idx on public.cdk_redemptions(email);
create index if not exists cdk_redemptions_status_idx on public.cdk_redemptions(status);

alter table public.cdk_redemptions enable row level security;

comment on table public.cdk_redemptions is 'CDK 卡密兑换记录';
comment on column public.cdk_redemptions.session_data is '用户提供的 ChatGPT Session 数据（完整 JSON 字符串）';
comment on column public.cdk_redemptions.card_code_hint is '卡密前几位提示（非完整卡密）';
comment on column public.cdk_redemptions.redemption_token is 'Zovocard 返回的兑换令牌';

